SELECT NOME AS NOME_DO_CLIENTE,
(CASE
WHEN TO_CHAR(DATA_DE_NASCIMENTO,'YYYY') < 1990 THEN 'VELHOS'
WHEN TO_CHAR(DATA_DE_NASCIMENTO,'YYYY') >= 1990 AND TO_CHAR(DATA_DE_NASCIMENTO,'YYYY') < 1995  THEN 'JOVENS'
ELSE 'CRIANCA'
END) AS CLASSIFICACAO
FROM TABELA_DE_CLIENTES

SELECT * FROM TABELA_DE_CLIENTES
