SELECT * FROM TB_PRODUTOS
WHERE SABOR = 'Manga'

SELECT * FROM TB_PRODUTOS
WHERE SABOR = 'Manga' OR TAMANHO = '470 ml'

SELECT * FROM TB_PRODUTOS
WHERE SABOR = 'Manga' AND TAMANHO = '470 ml'


SELECT * FROM TB_PRODUTOS
WHERE  NOT (SABOR = 'Manga' AND TAMANHO = '470 ml');


SELECT * FROM TB_PRODUTOS
WHERE  NOT (SABOR = 'Manga' OR TAMANHO = '470 ml');


SELECT * FROM TB_PRODUTOS
WHERE  SABOR = 'Manga' AND NOT (TAMANHO = '470 ml');

SELECT * FROM TB_PRODUTOS
WHERE SABOR IN ('Laranja','Manga');

SELECT * FROM TB_PRODUTOS
WHERE SABOR = 'Laranja' OR SABOR ='Manga';

SELECT * FROM TB_CLIENTES
WHERE CIDADE IN ('Rio de Janeiro', 'São Paulo') AND IDADE > 20

SELECT * FROM TB_CLIENTES
WHERE CIDADE IN ('Rio de Janeiro', 'São Paulo') AND (IDADE >= 20 AND IDADE <= 22);






