SELECT NF.CPF, TC.NOME, TO_CHAR(DATA_VENDA, 'YYYY-MM') AS ANO_MES,
SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS,
MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC
ON TC.CPF = NF.CPF
GROUP BY NF.CPF,TC.NOME, TO_CHAR(DATA_VENDA, 'YYYY-MM')


SELECT X.CPF, X.NOME, X.ANO_MES,
X.QUANTIDADE_VENDAS , X.QUANTIDADE_LIMITE ,
CASE WHEN (X.QUANTIDADE_LIMITE - X.QUANTIDADE_VENDAS) < 0 THEN 'INVÁLIDA'
ELSE 'VÁLIDA' END STATUS_VENDAS,(1-(X.QUANTIDADE_LIMITE/X.QUANTIDADE_VENDAS)) * 100 AS PERCENTUAL
FROM (
SELECT NF.CPF, TC.NOME, TO_CHAR(DATA_VENDA, 'YYYY-MM') AS ANO_MES,
SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS,
MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC
ON TC.CPF = NF.CPF
GROUP BY NF.CPF,TC.NOME, TO_CHAR(DATA_VENDA, 'YYYY-MM')) X
WHERE (X.QUANTIDADE_LIMITE - X.QUANTIDADE_VENDAS) < 0
