SELECT 'O CLIENTE ' || TC.NOME || 'FATUROU ' ||
TO_CHAR(ROUND(SUM(INF.QUANTIDADE * INF.PRECO),2)) ||
' ANO ' || TO_CHAR(DATA_VENDA, 'YYYY') AS SENTENCA
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC
ON TC.CPF = NF.CPF
WHERE TO_CHAR(DATA_VENDA,'YYYY') = '2016'
GROUP BY TC.NOME, TO_CHAR(DATA_VENDA, 'YYYY')