#LEVANTANDO O VALOR FINANCEIRO DAS VENDAS PELO FATURAMENTO ANUAL

SELECT TO_CHAR(DATA_VENDA, 'YYYY'), SUM(QUANTIDADE * PRECO) AS FATURAMENTO
FROM NOTAS_FISCAIS NF INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY TO_CHAR(DATA_VENDA,'YYYY')