SELECT SYSDATE FROM DUAL

SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH:MM:SS') FROM DUAL

SELECT SYSDATE + 10 FROM DUAL

SELECT SYSDATE - 10 FROM DUAL

SELECT MONTHS_BETWEEN(SYSDATE, TO_DATE('2021-01-01',  'YYYY/MM/DD')) FROM DUAL

SELECT ADD_MONTHS(SYSDATE, 10) FROM DUAL

SELECT NEXT_DAY(SYSDATE, 'QUARTA') FROM DUAL

SELECT LAST_DAY(SYSDATE) FROM DUAL

SELECT TRUNC(SYSDATE,'YEAR')FROM DUAL

SELECT TRUNC(SYSDATE,'MONTH')FROM DUAL

SELECT ROUND(SYSDATE,'YEAR')FROM DUAL

SELECT ROUND(SYSDATE,'MONTH')FROM DUAL

SELECT ROUND(SYSDATE - 20,'MONTH')FROM DUAL
