SELECT * FROM TB_CLIENTES;

SELECT CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, 
IDADE, SEXO, LIMITE_CREDITO, PRIMEIRA_COMPRA, DATA_NASCIMENTO FROM TB_CLIENTES;

SELECT CPF, NOME FROM TB_CLIENTES;

SELECT CPF AS IDENTIFICADO, NOME AS CLIENTE FROM TB_CLIENTES;

SELECT * FROM TB_PRODUTOS
WHERE SABOR = 'Uva';

SELECT * FROM TB_PRODUTOS
WHERE SABOR = 'Laranja';

SELECT * FROM TB_PRODUTOS
WHERE EMBALAGEM = 'PET'


SELECT * FROM TB_PRODUTOS
WHERE EMBALAGEM = 'pet'

SELECT * FROM TB_PRODUTOS
WHERE PRECO_LISTA > 19.50










