SELECT * FROM TABELA_DE_VENDEDORES;

SELECT * FROM NOTAS_FISCAIS;

SELECT MATRICULA,  COUNT(*) AS NUMERO_NOTAS FROM NOTAS_FISCAIS
GROUP BY MATRICULA;

SELECT * FROM NOTAS_FISCAIS A 
INNER JOIN TABELA_DE_VENDEDORES B 
ON B.MATRICULA = A.MATRICULA;

SELECT A.MATRICULA, B.NOME, COUNT(*) FROM NOTAS_FISCAIS A 
INNER JOIN TABELA_DE_VENDEDORES B 
ON B.MATRICULA = A.MATRICULA
GROUP BY A.MATRICULA, B.NOME;


