SELECT * FROM TB_CLIENTES

SELECT *FROM TB_PRODUTOS

SELECT CPF, NOME, SEXO,IDADE, DATA_NASCIMENTO FROM TB_CLIENTES;

SELECT IDADE,CPF, NOME, SEXO, DATA_NASCIMENTO FROM TB_CLIENTES;

SELECT CPF AS CPF_CLIENTE, NOME AS NOME_DO_CLIENTE, SEXO,IDADE, DATA_NASCIMENTO FROM TB_CLIENTES;