SELECT * FROM TB_VENDEDORES

SELECT TO_CHAR (DATA_ADMISSAO, 'MM') FROM TB_VENDEDORES

ALTER TABLE TB_VENDEDORES ADD DATA_ADMISSAO DATE
ALTER TABLE TB_VENDEDORES ADD DE_FERIAS NUMBER(1)

ALTER TABLE TB_VENDEDORES ADD CONSTRAINT PK_TB_VENDEDORES 
PRIMARY KEY (MATRICULA)

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS)
VALUES
('00235','Márcio Almeida Silva', 0.08, TO_DATE('15/03/2014', 'DD/MM/YYYY'), 0);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS)
VALUES
('00236','Cláudia Morais', 0.08, TO_DATE('17/09/2013', 'DD/MM/YYYY'), 1);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS)
VALUES
('00237','Roberta Martins', 1.1, TO_DATE('18/03/2017', 'DD/MM/YYYY'), 1);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS)
VALUES
('00238','Péricles Alves', 1.1, TO_DATE('21/08/2017', 'DD/MM/YYYY'), 0)

DROP TABLE TB_VENDEDORES


