SELECT * FROM TB_PRODUTOS

INSERT INTO TB_PRODUTOS (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES
('1078680', 'Frescor do Verão - 470 ml - Manga', 'Lata', '470 ml','Manga',5.18);
UPDATE TB_PRODUTOS SET EMBALAGEM = 'Garrafa' WHERE PRODUTO = '1078680';


ALTER TABLE TB_PRODUTOS ADD CONSTRAINT PK_TB_PRODUTOS
PRIMARY KEY (PRODUTO); 

DESC TB_PRODUTOS

